openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: This is the API documentation for our application.
servers:
  - url: http://localhost:3000
paths:
  /api/example:
    get:
      summary: Retrieve a list of examples
      description: Get all example items from the API.
      responses:
        200:
          description: A list of examples.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string